// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeOptimizer.Infrastructure.Data;

#nullable disable

namespace RecipeOptimizer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RecipeOptimizer.Domain.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dough"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Olives"
                        });
                });

            modelBuilder.Entity("RecipeOptimizer.Domain.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 2,
                            IngredientId = 6
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 2,
                            IngredientId = 7
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 3,
                            IngredientId = 2
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 6,
                            IngredientId = 1
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 6,
                            IngredientId = 3
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 8,
                            IngredientId = 4
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 10,
                            IngredientId = 5
                        });
                });

            modelBuilder.Entity("RecipeOptimizer.Domain.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Feeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feeds = 1,
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 2,
                            Feeds = 1,
                            Name = "Pie"
                        },
                        new
                        {
                            Id = 3,
                            Feeds = 1,
                            Name = "Sandwich"
                        },
                        new
                        {
                            Id = 4,
                            Feeds = 2,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 5,
                            Feeds = 3,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 6,
                            Feeds = 4,
                            Name = "Pizza"
                        });
                });

            modelBuilder.Entity("RecipeOptimizer.Domain.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 4,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 5,
                            Quantity = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 5,
                            Quantity = 2,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 1,
                            Quantity = 2,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 5,
                            Quantity = 1,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 6,
                            Quantity = 1,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 5,
                            Quantity = 2,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 11,
                            IngredientId = 3,
                            Quantity = 1,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 12,
                            IngredientId = 4,
                            Quantity = 2,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 13,
                            IngredientId = 1,
                            Quantity = 1,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 14,
                            IngredientId = 2,
                            Quantity = 2,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 15,
                            IngredientId = 3,
                            Quantity = 2,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 16,
                            IngredientId = 6,
                            Quantity = 1,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 17,
                            IngredientId = 4,
                            Quantity = 2,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 18,
                            IngredientId = 7,
                            Quantity = 1,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 19,
                            IngredientId = 5,
                            Quantity = 3,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 20,
                            IngredientId = 3,
                            Quantity = 2,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 21,
                            IngredientId = 4,
                            Quantity = 3,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 22,
                            IngredientId = 7,
                            Quantity = 1,
                            RecipeId = 6
                        });
                });

            modelBuilder.Entity("RecipeOptimizer.Domain.Models.Inventory", b =>
                {
                    b.HasOne("RecipeOptimizer.Domain.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RecipeOptimizer.Domain.Models.RecipeIngredient", b =>
                {
                    b.HasOne("RecipeOptimizer.Domain.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeOptimizer.Domain.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeOptimizer.Domain.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
